/**
 * Base File Converter Class
 * Provides common interface and functionality for all file format converters
 */

class FileConverter {
  constructor(formatName, supportedExtensions = []) {
    this.formatName = formatName;
    this.supportedExtensions = supportedExtensions;
    this.defaultOptions = {
      units: 'mm',
      coordinateSystem: 'absolute',
      feedRate: 100,
      spindleSpeed: 1000,
      toolDiameter: 3.175,
      stepDown: 1,
      stepOver: 0.5,
      safeHeight: 5,
      formatSpecific: {},
    };
  }

  /**
   * Detect if this converter can handle the given file
   * @param {string} filename - Name of the file
   * @param {Buffer|string} content - File content
   * @returns {Object} Detection result with confidence score
   */
  detect(filename, content) {
    const extension = this.getFileExtension(filename);
    const isExtensionSupported = this.supportedExtensions.includes(extension);

    if (isExtensionSupported) {
      return {
        canHandle: true,
        confidence: 0.8,
        format: this.formatName,
        reason: `File extension .${extension} is supported`,
      };
    }

    // Content-based detection (override in subclasses)
    const contentDetection = this.detectByContent(content);
    return {
      canHandle: contentDetection.canHandle,
      confidence: contentDetection.confidence || 0.1,
      format: this.formatName,
      reason: contentDetection.reason || 'Content analysis',
    };
  }

  /**
   * Content-based detection (override in subclasses)
   * @param {Buffer|string} content - File content
   * @returns {Object} Detection result
   */
  detectByContent(content) {
    return { canHandle: false, confidence: 0, reason: 'No content detection implemented' };
  }

  /**
   * Convert file to G-code
   * @param {Buffer|string} content - File content
   * @param {Object} options - Conversion options
   * @returns {Promise<Object>} Conversion result
   */
  async convert(content, options = {}) {
    throw new Error('convert() method must be implemented by subclasses');
  }

  /**
   * Validate converted G-code program
   * @param {string} gcode - Generated G-code
   * @returns {Object} Validation result
   */
  validate(gcode) {
    const lines = gcode.split('\n').filter(line => line.trim());
    const warnings = [];
    const errors = [];

    // Basic G-code validation
    lines.forEach((line, index) => {
      const trimmedLine = line.trim();

      // Skip comments and empty lines
      if (trimmedLine.startsWith('(') || trimmedLine.startsWith(';') || !trimmedLine) {
        return;
      }

      // Check for basic G-code structure
      if (!/^[GMF]\d+/i.test(trimmedLine) && !/^[XYZ]-?\d+/i.test(trimmedLine)) {
        warnings.push({
          line: index + 1,
          message: `Line may not be valid G-code: ${trimmedLine}`,
          severity: 'warning',
        });
      }
    });

    return {
      isValid: errors.length === 0,
      errors,
      warnings,
      lineCount: lines.length,
      statistics: {
        totalLines: lines.length,
        movementLines: lines.filter(line => /G[01]/i.test(line)).length,
        rapidMoves: lines.filter(line => /G0/i.test(line)).length,
        feedMoves: lines.filter(line => /G1/i.test(line)).length,
      },
    };
  }

  /**
   * Get file extension from filename
   * @param {string} filename - File name
   * @returns {string} File extension (lowercase, without dot)
   */
  getFileExtension(filename) {
    return filename.split('.').pop().toLowerCase();
  }

  /**
   * Merge user options with defaults
   * @param {Object} userOptions - User-provided options
   * @returns {Object} Merged options
   */
  mergeOptions(userOptions = {}) {
    return {
      ...this.defaultOptions,
      ...userOptions,
      formatSpecific: {
        ...this.defaultOptions.formatSpecific,
        ...(userOptions.formatSpecific || {}),
      },
    };
  }

  /**
   * Generate G-code header with setup commands
   * @param {Object} options - Conversion options
   * @returns {string} G-code header
   */
  generateHeader(options) {
    const header = [];

    header.push('(Generated by Arctos Robot Controller)');
    header.push('(File Converter: ' + this.formatName + ')');
    header.push('(Generated: ' + new Date().toISOString() + ')');
    header.push('');

    // Set units
    if (options.units === 'mm') {
      header.push('G21 ; Set units to millimeters');
    } else {
      header.push('G20 ; Set units to inches');
    }

    // Set coordinate system
    if (options.coordinateSystem === 'absolute') {
      header.push('G90 ; Absolute positioning');
    } else {
      header.push('G91 ; Incremental positioning');
    }

    // Set initial feed rate
    header.push('G94 ; Feed rate per minute');
    header.push(`F${options.feedRate} ; Set feed rate`);

    // Spindle setup
    if (options.spindleSpeed > 0) {
      header.push(`S${options.spindleSpeed} ; Set spindle speed`);
      header.push('M3 ; Start spindle clockwise');
    }

    // Move to safe height
    header.push(`G0 Z${options.safeHeight} ; Move to safe height`);
    header.push('');

    return header.join('\n');
  }

  /**
   * Generate G-code footer with cleanup commands
   * @param {Object} options - Conversion options
   * @returns {string} G-code footer
   */
  generateFooter(options) {
    const footer = [];

    footer.push('');
    footer.push('; End of program');
    footer.push(`G0 Z${options.safeHeight} ; Move to safe height`);
    footer.push('M5 ; Stop spindle');
    footer.push('G0 X0 Y0 ; Return to origin');
    footer.push('M30 ; End program');

    return footer.join('\n');
  }

  /**
   * Format coordinate value with proper precision
   * @param {number} value - Coordinate value
   * @param {number} precision - Decimal places
   * @returns {string} Formatted coordinate
   */
  formatCoordinate(value, precision = 3) {
    return parseFloat(value.toFixed(precision)).toString();
  }

  /**
   * Calculate bounding box of path points
   * @param {Array} points - Array of {x, y, z} points
   * @returns {Object} Bounding box {min: {x,y,z}, max: {x,y,z}}
   */
  calculateBoundingBox(points) {
    if (!points || points.length === 0) {
      return { min: { x: 0, y: 0, z: 0 }, max: { x: 0, y: 0, z: 0 } };
    }

    const min = { x: Infinity, y: Infinity, z: Infinity };
    const max = { x: -Infinity, y: -Infinity, z: -Infinity };

    points.forEach(point => {
      if (point.x < min.x) {
        min.x = point.x;
      }
      if (point.y < min.y) {
        min.y = point.y;
      }
      if (point.z < min.z) {
        min.z = point.z;
      }
      if (point.x > max.x) {
        max.x = point.x;
      }
      if (point.y > max.y) {
        max.y = point.y;
      }
      if (point.z > max.z) {
        max.z = point.z;
      }
    });

    // Handle infinite values
    Object.keys(min).forEach(key => {
      if (!isFinite(min[key])) {
        min[key] = 0;
      }
      if (!isFinite(max[key])) {
        max[key] = 0;
      }
    });

    return { min, max };
  }
}

module.exports = FileConverter;
